pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = 'command-keybind'

include 'common'
include 'mod-1_16'
include 'mod-1_18'
include 'mod-1_19_2'
include 'mod-1_19_4'
include 'mod-1_20_1'
include 'mod-1_20_6'
include 'mod-26_1'
include 'mod-26_2'
