plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'java-library'
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(8)
	}
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_1_8
	targetCompatibility = JavaVersion.VERSION_1_8
}

loom {
	mods {
		"command-keybind" {
			sourceSet sourceSets.main
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version_1_16}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version_1_16}"

	implementation project(':common')
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

jar {
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE
	from project(':common').sourceSets.main.output
}

remapJar {
	archiveFileName = "command-keybind-${project.version}-mc${project.minecraft_version_1_16}.jar"
}
